-- ⚠️ AUTOGENERATED FILE. DO NOT EDIT DIRECTLY.
-- Generated by scripts/gen-sql.mjs

create table if not exists "public"."goals" (
  "id" uuid not null default gen_random_uuid(),
  "user_id" uuid not null,
  "title" text not null,
  "why" text not null,
  "deadline" date,
  "image" text,
  "status" text not null default '0%',
  "category" text,
  "important" text,
  "created_at" timestamp with time zone not null default now(),
  primary key ("id"),
  foreign key ("user_id") references "auth"."users" ("id") on delete cascade
);

create index if not exists "goals_user_id_created_at_idx" on "public"."goals" ("user_id", "created_at");

comment on table "public"."goals" is 'Lagrer mål knyttet til en innlogget bruker, inkludert motivasjon, status og metadata for visning i appen.';
comment on column "public"."goals"."id" is 'Primærnøkkel som identifiserer målet.';
comment on column "public"."goals"."user_id" is 'Referanse til Supabase-brukeren som eier målet.';
comment on column "public"."goals"."title" is 'Kort tittel som beskriver målet.';
comment on column "public"."goals"."why" is 'Brukerens begrunnelse for hvorfor målet er viktig.';
comment on column "public"."goals"."deadline" is 'Valgfri sluttdato for målet.';
comment on column "public"."goals"."image" is 'Data-URL eller ekstern lenke til forsidebildet for målet.';
comment on column "public"."goals"."status" is 'Prosentvis progresjon lagret som tekst (for eksempel ''25%'').';
comment on column "public"."goals"."category" is 'Valgfri kategori som målet tilhører.';
comment on column "public"."goals"."important" is 'Fritekstfelt som beskriver hvorfor målet er viktigst akkurat nå.';
comment on column "public"."goals"."created_at" is 'Tidspunkt da målet ble opprettet.';
